// layout.tsx

import type { Metadata } from "next";
import "./globals.css";

const font = "Arial"; // Specify the Arial font

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{ fontFamily: font }} className="checked-border">
        <div className="container mx-auto px-4">{children}</div>
      </body>
    </html>
  );
}
